version: "3"
services:
  client:
    image: "duong1200798/multi-client"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: react-client
  server:
    image: "duong1200798/multi-server"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: api-server
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST

      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

      - SERVER_PORT=$SERVER_PORT
  worker:
    image: "duong1200798/multi-worker"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "duong1200798/multi-nginx"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: nginx
    ports:
      - "80:80"
