apiVersion: v1
kind: Service
metadata:
  name: stateful-service-name
spec:
  ClusterIP: ""
  selector:
    component: app
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-stateful
spec:
  serviceName: stateful-service-name # the name of service
  replicas: 2
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: nginx:alpine
          ports:
            - containerPort: 80
      volumeMounts:
        - name: volume-use-pvc
          mountPath: /usr/share/nginx/html/
  volumeClaimTemplates: # pvc template
    metadata:
      name: volume-use-pvc
    spec:
      resources:
        requests:
          storage: 1Mi
        accessModes:
          - ReadWriteOnce

