apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  default.conf: |
    server {
        listen 80;

        gzip on;
        gzip_types text/plain application/xml;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;

            try_files $uri $uri/ /index.html;
        }
    }