apiVersion: v1
kind: Pod
metadata:
  name: aws-cloud-storage-volumes
spec:
  containers:
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: aws-volumes
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: aws-volumes
      awsElasticBlockStore: # using AWS ElasticBlockStore instead of gcePersistentDisk
        volumeID: "vol-0f5ce9f935074354d"
        fsType: ext4