version: '3'

services:
  redis-server:
    container_name: 'redis-server'
    image: 'redis'
    networks:
      - node-redis
    ports:
      - '6379:6379'  
  node-app:
    container_name: 'node'
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    networks:
      - node-redis
    working_dir: /usr/src/app
    volumes:
          - ./:/usr/src/app
          - /usr/src/app/node_modules
volumes:
    node-volumes:

networks:
  node-redis: