apiVersion: v1
kind: Pod
metadata:
  name: pod-use-pvc
spec:
  label:
    component: mongo-db
  containers:
    - name: mongo-db
      image: mongodb
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      port:
        - containerPort: 27017
          protocol: TCP
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:
        claimName: persistent-volume-claim # name of persistent-volume-claim defined
