apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server # label of pod container
  ports:
    - port: 3051 # this port of service
      targetPort: 5001 # port of server container